### PR TITLE
website changes

### PR DESCRIPTION
**Pull request by davidmallett93**
What? Added link to TicTacToe game of mine. 
Why? To show off my awesome game. 
How? Via Git, VSCode, & LiveServer
Testing? Via LiveServer
Screenshots (optional) see below
Anything Else? No
Screenshot 2024-05-14 at 3 36 06 PM
Screenshot 2024-05-14 at 3 36 33 PM

### CODE REVIEW

**Review by SeanJPeterson — COMMENTED** [review]
Looks very good! Did you make sure to change your "Contact" button to "My Project" and linked it to your TicTacToe project?

**Comment by davidmallett93** [comment]
> Looks very good! Did you make sure to change your "Contact" button to "My Project" and linked it to your TicTacToe project?

Yeah I did.

**Review by SeanJPeterson — APPROVED** [review]
Looks good David! Good job!

**Comment by NFARAdmin** [comment]
Hi David, 

Did you double check on your TicTacToe.html page if it navigates to the home page correctly? From the top left in the TicTacToe.html page, click on the "hamburger" menu and check if the Home button navigates to the home page. 

Also, there are only 3 files submitted. The index.html file is unmodified in this branch.

**Review by NFARAdmin — APPROVED** [review]
All 4 files are there. Looks like you updated Brian's typo as well. Let him know.

**Pull request merged**
