### PR TITLE
New Pull Request w/ Photo

### PR DESCRIPTION
**Pull request by E-F-R**
What - made changes to Card 3
Why - made card more personable with new photo and slight bio modification
How - used VSCode as framework
Testing - opening code using VSCode Live Server to ensure code functions without error
Screen Shot 2024-04-30 at 2 32 01 PM

### CODE REVIEW

**Comment by HeyzuseEtRex** [comment]
Full  Name: Check
DMV Mug Shot: Check
Personal  Bio: Check
Squared and leveled Card: Check
Code included: Check

**Comment by NFARAdmin** [comment]
This was reopened

**Review by aarondknopp — APPROVED** [review]
These changes appear to fit the bill and should be easy to integrate.

**Comment by HeyzuseEtRex** [comment]
Full Name: Check
Profile Pic: Check
Personal Bio: Check
Squared and leveled Card: Check
Code included: Check

**Pull request merged**
