### PR TITLE
commiting changes

### PR DESCRIPTION
**Pull request by ChristianFaelschle**
- What? Upload image for Cohort6 image.
- Why? The image was provided by the team leader.
- How? Uploaded locally and committed branch.
- Testing? Reviewed image in VS Code live server and it is the correct image.
- Screenshots (optional)
- Anything Else? Nothing else.
- 
Screenshot 2024-04-30 at 3 01 26 PM

### CODE REVIEW

**Review by NFARAdmin — CHANGES_REQUESTED** [review]
Hi C. 
Need to change the email to end .net (it has .com). 

Your picture was not uploaded. Don't forget a screenshot.

**Comment by aarondknopp** [comment]
These changes appear to be fitting for the website.

**Review by davidmallett93 — APPROVED** [review]
This looks good, Christian.

**Review by NFARAdmin — APPROVED** [review]

**Review by NFARAdmin — APPROVED** [review]
Changes that were requested were submitted.

**Pull request merged**
